definitions:
  http.APIResponse:
    properties:
      count:
        type: integer
      data: {}
      error:
        $ref: '#/definitions/http.Status'
      pages:
        type: integer
    type: object
  http.Status:
    properties:
      internalError:
        type: string
      message:
        type: string
      ok:
        type: boolean
    type: object
  transport.CreateListReq:
    properties:
      description:
        type: string
      name:
        type: string
    type: object
info:
  contact: {}
paths:
  /api/v1/lists:
    post:
      consumes:
      - application/json
      description: Creates a new list with the provided details
      operationId: create-list
      parameters:
      - description: List details
        in: body
        name: list
        required: true
        schema:
          $ref: '#/definitions/transport.CreateListReq'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/http.APIResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/http.APIResponse'
      summary: Create a new list
      tags:
      - Lists
  /api/v1/lists/{id}:
    get:
      description: Gets a list by its ID
      operationId: get-list
      parameters:
      - description: List ID formatted as an UUID string
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/http.APIResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/http.APIResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/http.APIResponse'
        "405":
          description: Method Not Allowed
          schema:
            $ref: '#/definitions/http.APIResponse'
      summary: Get list by ID
      tags:
      - Lists
swagger: "2.0"
