definitions:
  http.APIResponse:
    properties:
      count:
        type: integer
      data: {}
      error:
        $ref: '#/definitions/http.Status'
      pages:
        type: integer
    type: object
  http.Status:
    properties:
      internalError:
        type: string
      message:
        type: string
      ok:
        type: boolean
    type: object
info:
  contact: {}
paths:
  /api/v1/lists/{id}:
    get:
      description: Gets a list by its UUID
      operationId: get-list
      parameters:
      - description: List UUID formatted as an UUID string
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/http.APIResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/http.APIResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/http.APIResponse'
        "405":
          description: Method Not Allowed
          schema:
            $ref: '#/definitions/http.APIResponse'
      summary: Get list by UUID
      tags:
      - Lists
swagger: "2.0"
